### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by SebastianM-C** [SciML/ModelingToolkitNeuralNets.jl#3]
There are a couple of things to do before registering the package:
- [x] bikeshed package name See #14 
- [x] bikeshed public API. See #9 
- [x] fix type piracy for `propagate_ndims` and `propagate_shape`. Fixed in #11 
- [x] fix CI setup (I tried adding some things based on PkgTemplates and LinearSolve, but I'm pretty sure it needs fixing) See #10
- [x] fix tests. While it worked on my machine™, in CI the weights might be too large. See #5 for details.
- [ ] figure out if we can do anything about the cache size in DAE initialization (the cache created by the nonlinear solve in the DAE initialization is resized on each gradient call). See #4 for details.
- [x] docs
- [x] readme

**Comment by ChrisRackauckas** [comment]
>  bikeshed public API

It needs to present itself like other component libraries. Right now, the public API does not match the way capitalization and naming is done in ModelingToolkitStandardLibrary.

**Comment by SebastianM-C** [comment]
The package is registered now 🎉
